INFURA/go-ethlibs

- node/websocket/websocket.go
- node/websocket/websocket_test.go
Previously we were incorrectly returning a pointer to a zero-value `eth.Block`.
> websocket: Return an error when user requests invalid blocks

- node/client.go
- node/custom.go
This adds support for building custom clients that implement the full `node.Client` interface by just supplying a `node.Requester` and optional `node.Subscriber` interface implementations.
This can be used for doing custom routing, for example to build a client which routes requests to different backends based on the JSONRPC request method (e.g. `parity_*` methods to a parity node, while sending other RPCs to geth).
> node: Add support for custom clients

- node/loop.go
Found a case where we weren't propagating the error during a read, which could lead to, for example, a `panic` in gorilla websocket when trying to read on the connection again:
```
panic: repeated read on failed websocket connection
goroutine 48 [running]:
github.com/gorilla/websocket.(*Conn).NextReader(0xc00033ab00, 0x1b30910, 0xc000433d98, 0x4de1bb, 0xc000462050, 0x0)
/go/src/github.com/INFURA/off-chain-logs/vendor/github.com/gorilla/websocket/conn.go:1001 +0x353
github.com/INFURA/go-ethlibs/node.newWebsocketTransport.func1(0xc000462040, 0x0, 0x0, 0x13b7a60, 0xc000d35360)
/go/src/github.com/INFURA/off-chain-logs/vendor/github.com/INFURA/go-ethlibs/node/websocket.go:25 +0x2e
```
> node: Fix missing return in bidirectional transport during read error

- node/_example/main.go
- node/interfaces.go
- node/loop.go
- node/subscription.go
Ok, I believe this resolves the root issue(s) uncovered by @JeeChoi in #11, namely:
- subscription having it's own context and cancel routine was definitely odd
- the channel returned by `subscription.Ch()` was never closed
However, when adding code to close the channel, I realized there was a more fundamental issue, in that the channel was being written to by multiple go routines, so closing the channel could lead to race conditions where writes occurred after close, leading to panics.  After researching solutions, the one I ended up liking best was a modified version of the code in "variant 5" one this page: https://go101.org/article/channel-closing.html 
I added a fair amount of comments since the number of channels ballooned from one to four, and also wrapped all the logic in private …
> Refactor subscriptions to avoid issues with channel ownership

- jsonrpc/id.go
- node/_example/main.go
- node/client.go
- node/context.go
- node/interfaces.go
This fixes #7 by allowing the node.Client consumer to specify a request ID on the context passed into client methods, for example:
```golang
block, err := client.BlockByHash(node.ContextWithRequestID(jsonrpc.StringID("test")), hash, true)
```
This is a requirement for some internal systems where we want to start using a custom request ID for routing inside the request receiver, even though that's not really the intended use of `id` (https://www.jsonrpc.org/specification#request_object) it beats adding any other metadata to the requests.
It's also useful for clients that want to use custom IDs to assist with general observability (e.g. using an auto-incrementing ID to track request counts, etc.).
Anyways, happy to discuss alternative implementations (ed: which were discussed and we landed …
> node.Client: Allow setting request options (namely request.ID). Fixes #7.

- go.mod
- go.sum
- node/loop.go
- node/websocket.go
This PR fixes some race conditions found in the websocket node.Client transport:
- Turns out gorilla/websocket is not concurrency safe, even though it implements functions from stdlib's `net.Conn` which is documented as concurrency safe.  As mentioned in the gorilla docs the read and write groupings of methods need to be protected, so I added `readMu` and `writeMu`.
- in loopingTransport.Request, we weren't actually copying the input Request when adding it to the outgoingRequest struct.  At first I tried basically `outgoing.request = &*r`, but even that's not enough: `jsonrpc.Request.Params` is a slice, so Go just copies over the slice address, so we have to do a "deep copy" and jinzhu's copier package seems to be the most commonly used way to do that.
- Stop closing the …
> Fix race conditions in websocket transport.

- node/ipc.go
- node/loop.go
- node/websocket.go
I found after some more testing the gorilla can deadlock with the changes from #18.  Luckily, I found that the gorilla docs mention that `.Close()` _is_ safe to call concurrently from other goroutines, so this seems like a cleaner approach.
While debugging I also changed to using `.DialContext` since we have a context, and removed some spammy log messages.
> Use Close instead of Deadlines, use DialContext.

- go.mod
- go.sum
- node/loop.go
This goes along with my other 2 (closed source) PRs that made reasoning about our heaps in `pprof` easier.
The main change is to stop using `copier.Copy` on the incoming `jsonrpc.Request` objects, since it doesn't actually seem to fully deep-copy our `jsonrpc.Params` type.  Since we were already using reflection to copy the struct, we might as well use our JSON encoding versus re-defining another approach.
> Make websocket memory usage easier to reason about in pprof.

- node/loop.go
I just ran into a corner case during a network issue when debugging locally that I'm pretty sure I traced back to this issue.
Normally `loopingTransport.ctx` and the `ctx` passed into `.Request` are the same, or at least in the same tree, but they don't have to be, so it's definitely a bug that we'd do `<-t.ctx.Done` but return `ctx.Err()`.  This led to the scenario where `.Request()` returned `(nil, nil)` which it shouldn't.
> Make sure we return the correct ctx.Err

- .circleci/config.yml
- eth/quantity.go
- eth/quantity_test.go
The issue was that Block.DeepCopy autogenerates code like:
```
*out := *in
in.Difficulty.DeepCopyInto(&out.Difficulty)
```
See: https://github.com/INFURA/go-ethlibs/blob/master/eth/zz_deepcopy_generated.go#L19
However, our hand-written `Quantity.DeepCopyInto` wasn't fully resetting the embedded `big.Int`, and `big.Int.nat.abs` is a `[]Word` slice so was being re-used, which could lead to data races if the blocks were accessed on different go-routines.
> Fix potential data race in Quantity.DeepCopyInto

- eth/transaction_signing.go
- eth/transaction_signing_test.go
I did some more testing of EIP-2930 signing and came across an issue where `Transaction.Sign` wasn't updating the `.Hash` field.  Since the data's available seems like there's no reason not to update the hash.
I've added a new EIP-2930 specific test for tx signing and updated the existing tests to confirm the hash value is correct.  Also renamed the test names to follow test naming conventions a bit more.
> eth: make sure Transaction.Hash is set by Transaction.Sign.

- eth/transaction_from_raw.go
- eth/transaction_from_raw_test.go
- eth/transaction_signing.go
- eth/transaction_signing_test.go
I was re-reviewing my `.Sign` changes and noticed that I left out an error check, which could lead to a panic on unsupported tx types (unit added to cover this case now).  
This in turn made me revisit `.FromRaw` since I noticed it didn't fully follow the EIP-2718 spec when inspecting the first byte, so I refactored that a bit as well.  The net result is that `FromRaw` now returns more informative/correct errors instead of trying to decode all non-EIP-2930 txs as legacy txs.
> eth.Transaction: Make the input validation for .FromRaw and .Sign more robust

- eth/data.go
- eth/signature.go
- eth/transaction_from_raw.go
- eth/transaction_from_raw_test.go
- eth/transaction_signing.go
- eth/transaction_signing_test.go
This PR does a cleanup pass on our signing ergonomics and fixes a few bugs along the way.  It turned into a rather large PR since it required changing to the signing and from raw processes.  The main goal is was to make the final code easier to follow and hopefully will make implementing new transaction types (e.g. EIP-1559) easier going forward.
- Adds a new `Transaction.SigningPreimage` function which helps make the code a little easier to read and test
- Moves the ChainId packing/unpacking and ECRecover functionality into `Signature` which enables
- Fixing a bug where `Transaction.From` was not set after calling `Transaction.Sign`
- Also fixes a regression where we were letting unsigned legacy txs get further along in the code than previously
- Adds `Transaction.Signature()` for …
> Transaction Signing Refactor

- eth/transaction_from_raw_test.go
- eth/transaction_signing.go
- eth/transaction_signing_test.go
This PR adds a simple `eth.Transaction.IsProtected() bool` method  that transaction consumers can use to ensure they are only processing transactions protected by EIP-155 or later protection mechanisms (e.g. all EIP-2930 txs are inherently replay protected since the chainId is included as a discrete field).
Also added a docstring to `eth.Transaction.Signature` that I missed in my last PR. 😊
> Add eth.Transaction.IsProtected method

- eth/transaction_from_raw_test.go
- eth/transaction_signing.go
Turns out we were never returning the correct `From` address when decoding unprotected EIP-155 transactions.  This is because we were treating all txs as EIP-155, and thus using `RLP(Nonce, GasPrice, Gas, To, Value, Input, ChainId, 0, 0)` as the signing pre-image (where ChainId was always `0`), but the correct pre-image for pre-EIP-155 unprotected transactions *those with `v=27` or `v=28`) is just the 6-element list `RLP(Nonce, GasPrice, Gas, To, Value, Input)` from the yellow paper Appendix F, equations `(287)`.
This PR fixes that and ensures that our unprotected tx test case inspects all the fields (prior to this PR the `From` field was wrong, all other fields were correct).
> bugfix: recover the correct From address for non-EIP-155 transactions

- eth/accesslist.go
- eth/transaction_signing_test.go
This is my attempt at fixing a nil pointer deference bug.
I ran across this bug when I tried to create a tx of type `TransactionTypeDynamicFee` without filling in an accessList and then sign that tx. 
The crash happens on this line: https://github.com/INFURA/go-ethlibs/blob/e0d82d62fa8f55cd0ef5b7804fbfe61e1255ccd8/eth/transaction_signing.go#L155
I was using the other unit-tests as references but I wasn't sure how some of the values were filled out so left them as a TODO. Did you use another library to sign/send the tx to get the txhash, signed values etc?
> return empty accesslist rlp

- node/client.go
- node/interfaces.go
- node/ropsten_test.go
Small PR for adding ChainId support to go-ethlibs. 
`go test node/ropsten_test.go -v`
<details>
```bash
➜  go-ethlibs git:(add-chain-id-rpc) ✗ go test node/ropsten_test.go -v
=== RUN   TestConnection_GetTransactionCount
--- PASS: TestConnection_GetTransactionCount (0.41s)
=== RUN   TestConnection_EstimateGas
--- PASS: TestConnection_EstimateGas (0.15s)
=== RUN   TestConnection_MaxPriorityFeePerGas
--- PASS: TestConnection_MaxPriorityFeePerGas (0.16s)
=== RUN   TestConnection_GasPrice
--- PASS: TestConnection_GasPrice (0.19s)
=== RUN   TestConnection_NetVersion
--- PASS: TestConnection_NetVersion (0.21s)
=== RUN   TestConnection_ChainId
--- PASS: TestConnection_ChainId (0.18s)
=== RUN   TestConnection_SendRawTransactionInValidEmpty
--- PASS: TestConnection_SendRawTransactionInValidEmpty …
```
> Add ChainId

- node/http.go
Previously the 0-value transport had `.IdleConnTimeout: 0` which means idle timeouts were disabled, and thus connections were only closed if the underlaying TCP connection timed out.  I also now copy the `MaxIdleConns` value since that was the semantic intent of setting the value to 100.
> fix(node): use cloned DefaultTransport to setup correct default values

- .circleci/config.yml
- jsonrpc/request.go
- jsonrpc/request_test.go
Using this package in Palm user facing monitoring and I use it in blockNumber() to compare with the BlockNumber from Palm explorer
Tried to send a request without Params and I had that error "Method, params, and jsonrpc, are all required parameters" 
Then I add Params but same error because Params is nil 
I remove the omitempty from Params tags, the request's working
Then, I add unit test TestMarsalGoodRequests to confirm if in anycase I have Params[] and jsonrpc 2.0
This change should not have any impact on the other repo using this package
This PR is consistent with the API reference https://eth.wiki/json-rpc/API where params is always defined even if empty.
> fix(jsonrpc):remove omitempty of Params fields in MarshalJSON()

- eth/block_specifier.go
- eth/block_specifier_test.go
These methods had to be prefixed with `Get`, as opposed
to the equivalents elsewhere, because of the existing named
public fields of the struct.
> feat: add Get* helper methods to eth.BlockSpecifier

- eth/block.go
- eth/block_from_raw.go
- eth/block_from_raw_test.go
- eth/block_test.go
- eth/data.go
- eth/withdrawals.go
Ok, this is now rebased off master w/ (#68) and squashed and all items from our session this morning are almost [^1] all resolved, so ready to take another look.
[^1]: my guess is we end up sticking w/ `address` and the JSONRPC spec is updated to replace `recipient` w/ `address` since that more closely matches the consensus layer and EIP specs. https://github.com/ethereum/execution-apis/issues/378
> eth.Block: add support for EIP-4895 withdrawals

- eth/new_heads.go
I don't have a Zhejiang node running locally and the public nodes don't support websockets, but looking at the geth code it looks like the withdrawal root would be included in `newHeads` subscription results since it's a header field (the withdrawals themselves won't be since only header fields are included).
> eth.NewHeadsResult: Add EIP-4895 WithdrawalsRoot

- eth/block.go
- eth/block_test.go
- eth/zz_deepcopy_generated.go
- Fixes #87. 
- Fixes #90. 
It's all pretty straight-forward and simply new optional `Quantity` and `Hash` fields in `eth.Block`.
> eth.Block: Add fields for EIP-4788 and EIP-4844

- eth/transaction.go
- eth/transaction_test.go
This was spotted by @ggarri, the extra `return nil` isn't needed and should be removed.
I considered calling `RequiredFields` inside `Transaction.UnmarshallJSON` but ultimately decided against that since it seemed like too much of a behavorial changes, and I can see a use case where someone wants to unmarshal are partial tx w/o error, and they can always call `.RequiredFields` separately like I do in the unit test.
I also noticed that two of the older unit tests were missing `chainId` fields so added those.
> eth.Transaction: fix RequiredFields behavior for legacy transactions

- eth/authorizationlist.go
- eth/authorizationlist_test.go
- eth/transaction.go
- eth/transaction_from_raw.go
- eth/transaction_from_raw_test.go
- eth/transaction_signing.go
- eth/transaction_signing_test.go
- eth/transaction_test.go
This adds EIP-7702 "setcode" transactions types as defined in the EIP:
https://eips.ethereum.org/EIPS/eip-7702#set-code-transaction
> feat(eth): add support for EIP-7702 transactions
